#ifndef G_GAMESTATE
#define G_GAMESTATE
typedef enum g_gamestate
{
    GAMESTATE_STARTSCREEN,
    GAMESTATE_MAINMENU,
    GAMESTATE_PLEASE_WAIT,
    GAMESTATE_PLAYING,
    GAMESTATE_CHOOSE_EPISODE,
    GAMESTATE_CHOOSE_DIFFICULTY,
    GAMESTATE_CONFIG,
    GAMESTATE_CONFIG_SELECTED,
    GAMSTATE_CHEAT_MENU,
    GAMESTATE_LOAD,
    GAMESTATE_SAVE,
    GAMESTATE_LEVELCOMPLETE,
    GAMESTATE_ORDERNOW
}g_gamestate;
#endif